---
title: "MobNet Usage"
author: "Keith J. Yoder"
date: "March 3, 2022"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    toc: yes
    toc_float: yes
---

# Import `keras` and the trained model
```{r setup}
require(keras)
model <- load_model_hdf5('MobNet_TOB2.h5')
```

# Reproduce the character lookup table
```{r character_lookup}
character_lookup <- data.frame(character = c(letters,".","-"," ","+"))
character_lookup[["character_id"]] <- 1:nrow(character_lookup)
character_lookup$character <- as.character(character_lookup$character)
max_length <- 10
```

# Write a function to generate a new monster name
```{r generate_name_func}
generate_name <- function(model, character_lookup, max_length, temperature = 1){
  choose_next_char <- function(preds, character_lookup, temperature){
    preds <- log(preds)/temperature
    exp_preds <- exp(preds)
    preds <- exp_preds/sum(exp(preds))
    next_index <- which.max(as.integer(rmultinom(1, 1, preds)))
    character_lookup$character[next_index-1]
  }
  
  in_progress_name <- character(0)
  next_letter <- ""
  
  while(next_letter != "+" && length(in_progress_name) < 30){
    previous_letters_data <- 
      lapply(list(in_progress_name), function(.x){
        character_lookup$character_id[match(.x,character_lookup$character)]
      })
    previous_letters_data <- pad_sequences(previous_letters_data,
                                           maxlen = max_length)
    previous_letters_data <- to_categorical(previous_letters_data,
                                            num_classes = 31)
    
    next_letter_probabilities <- 
      predict(model,previous_letters_data)
    
    next_letter <- choose_next_char(next_letter_probabilities,
                                    character_lookup,
                                    temperature)
    
    if(next_letter != "+")
      in_progress_name <- c(in_progress_name,next_letter)
  }
  
  raw_name <- paste0(in_progress_name, collapse="")
  
  capitalized_name <-gsub("\\b(\\w)","\\U\\1",raw_name,perl=TRUE)
  
  capitalized_name
}
```

# AI-generated names

## Single name
```{r generate_one}
generate_name(model, character_lookup, max_length)
```

## 40 names
```{r generate_40}
sapply(1:40, function(x) {
  generate_name(model, character_lookup, max_length)
})
```



